Repository pagopa/pagopa-backoffice-external, pull requests merged in 2024-03, with the labels that each got.

#4 fix: Updated Dockerfile to reference proper JarLauncher package
  .github/workflows/code_review.yml
  Dockerfile
  pom.xml
Labels: size/small

#5 chore: updated Dockerfile base images versions
  Dockerfile
Labels: size/small

#8 ingress
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  infra/04_apim_api.tf
  infra/policy/_base_policy.xml
Labels: size/small

#9 fix infra
  infra/04_apim_api.tf
  openapi/generate_openapi.sh
  openapi/openapi.json
  openapi/openapi_backoffice_external.json
  openapi/openapi_backoffice_helpdesk.json
  postman-collection/backoffice-external.postman_collection.json
  src/main/java/it/pagopa/selfcare/pagopa/config/OpenApiConfig.java
  src/main/java/it/pagopa/selfcare/pagopa/controller/ExternalController.java
  src/main/java/it/pagopa/selfcare/pagopa/controller/OperativeTableController.java
Labels: size/large

#10 [VAS-814] feat: Add filter to operative table api
  openapi/openapi.json
  openapi/openapi_backoffice_helpdesk.json
  postman-collection/backoffice-external.postman_collection.json
  src/main/java/it/pagopa/selfcare/pagopa/controller/OperativeTableController.java
  src/main/java/it/pagopa/selfcare/pagopa/repository/OperativeTableRepository.java
  src/main/java/it/pagopa/selfcare/pagopa/service/OperativeTableService.java
  src/main/java/it/pagopa/selfcare/pagopa/service/impl/OperativeTableServiceImpl.java
  src/test/java/it/pagopa/selfcare/pagopa/controller/OperativeTableControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/service/impl/OperativeTableServiceImplTest.java
Labels: enhancement, size/small

#11 [VAS-841] Update business name filter to be case-insensitive
  src/main/java/it/pagopa/selfcare/pagopa/repository/OperativeTableRepository.java
  src/main/java/it/pagopa/selfcare/pagopa/service/impl/OperativeTableServiceImpl.java
  src/test/java/it/pagopa/selfcare/pagopa/service/impl/OperativeTableServiceImplTest.java
Labels: enhancement, size/small

#13 chore: Change productID selfcare helpdesk
  infra/04_apim_api.tf
Labels: size/small

#15 chore: swagger config
  openapi/openapi.json
  openapi/openapi_backoffice_external_ec.json
  openapi/openapi_backoffice_external_psp.json
  openapi/openapi_backoffice_helpdesk.json
  pom.xml
  src/main/java/it/pagopa/selfcare/pagopa/config/OpenApiConfig.java
  src/main/java/it/pagopa/selfcare/pagopa/config/TableOperationCustomizer.java
Labels: size/large

#14 [VAS-754][VAS-851] feat: API for ibans filtered by brokerCode
  infra/04_apim_api.tf
  openapi/openapi.json
  openapi/openapi_backoffice_external_ec.json
  openapi/openapi_backoffice_external_psp.json
  openapi/openapi_backoffice_helpdesk.json
  src/main/java/it/pagopa/selfcare/pagopa/controller/ExternalController.java
  src/main/java/it/pagopa/selfcare/pagopa/controller/OperativeTableController.java
  src/main/java/it/pagopa/selfcare/pagopa/repository/BrokerIbansRepository.java
  src/main/java/it/pagopa/selfcare/pagopa/service/ExternalService.java
  src/main/java/it/pagopa/selfcare/pagopa/service/impl/ExternalServiceImpl.java
  src/test/java/it/pagopa/selfcare/pagopa/controller/ExternalControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/service/impl/ExternalServiceImplTest.java
Labels: enhancement

#16 fix: openapi
  openapi/openapi.json
  openapi/openapi_backoffice_external_ec.json
  openapi/openapi_backoffice_external_psp.json
  openapi/openapi_backoffice_helpdesk.json
Labels: bug

#17 fix swagger external
  openapi/openapi.json
  openapi/openapi_backoffice_external_ec.json
  openapi/openapi_backoffice_external_psp.json
  openapi/openapi_backoffice_helpdesk.json
  src/main/java/it/pagopa/selfcare/pagopa/config/OpenApiConfig.java
  src/main/java/it/pagopa/selfcare/pagopa/controller/ExternalController.java
Labels: size/large
