Repository pagopa/pagopa-backoffice-external, pull requests merged in 2024-07, with the labels that each got.

#26 [PPANTT-54] feat: introducing total counter to pageInfo on apis
  openapi/openapi.json
  openapi/openapi_backoffice_external_ec.json
  openapi/openapi_backoffice_external_psp.json
  openapi/openapi_backoffice_helpdesk.json
  src/main/java/it/pagopa/selfcare/pagopa/entities/BrokerInstitutionAggregate.java
  src/main/java/it/pagopa/selfcare/pagopa/entities/IbanAggregate.java
  src/main/java/it/pagopa/selfcare/pagopa/model/PageInfo.java
  src/main/java/it/pagopa/selfcare/pagopa/repository/BrokerIbansRepository.java
  src/main/java/it/pagopa/selfcare/pagopa/repository/BrokerInstitutionsRepository.java
  src/main/java/it/pagopa/selfcare/pagopa/service/impl/ExternalServiceImpl.java
  src/main/java/it/pagopa/selfcare/pagopa/util/PageInfoMapper.java
  src/test/java/it/pagopa/selfcare/pagopa/service/impl/ExternalServiceImplTest.java
Labels: size/large, minor

#27 [PPANTT-54] feat: Updated page counter formula
  src/main/java/it/pagopa/selfcare/pagopa/service/impl/ExternalServiceImpl.java
Labels: size/small, patch

#28 [PPANTT-54] feat: Updated hotfix-query
  src/main/java/it/pagopa/selfcare/pagopa/repository/BrokerInstitutionsRepository.java
Labels: size/small

#29 Aggregation ci iban
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_backoffice_external_ec.json
  openapi/openapi_backoffice_external_psp.json
  openapi/openapi_backoffice_helpdesk.json
  pom.xml
  src/main/java/it/pagopa/selfcare/pagopa/controller/ExternalController.java
  src/main/java/it/pagopa/selfcare/pagopa/repository/CreditorInstitutionIbansRepository.java
  src/main/java/it/pagopa/selfcare/pagopa/service/impl/ExternalServiceImpl.java
  src/main/java/it/pagopa/selfcare/pagopa/service/impl/UtilComponent.java
  src/test/java/it/pagopa/selfcare/pagopa/controller/ExternalControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/service/impl/ExternalServiceImplTest.java
Labels: size/large, patch
